version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3500:3500
    volumes:
      - ./
      - nodemodules:/src/node_modules
      - ./node_modules
    command: 
      - npm
      - start
volumes:
    nodemodules: {}