"use strict";
exports.__esModule = true;
exports.FurnitureBillRequest = exports.FurnitureCategoryRequest = exports.FurnitureUploadRequest = exports.FurnitureSocialMediaRequest = exports.FurnitureProductTypeRequest = exports.FurnitureAccessoryRequest = exports.FurnitureUserRequest = exports.FurnitureProductRequest = void 0;
var product_1 = require("./product");
var user_1 = require("./user");
var accessory_1 = require("./accessory");
var productType_1 = require("./productType");
var social_media_1 = require("./social-media");
var upload_1 = require("./upload");
var category_1 = require("./category");
var bill_1 = require("./bill");
exports.FurnitureProductRequest = product_1["default"];
exports.FurnitureUserRequest = user_1["default"];
exports.FurnitureAccessoryRequest = accessory_1["default"];
exports.FurnitureProductTypeRequest = productType_1["default"];
exports.FurnitureSocialMediaRequest = social_media_1["default"];
exports.FurnitureUploadRequest = upload_1["default"];
exports.FurnitureCategoryRequest = category_1["default"];
exports.FurnitureBillRequest = bill_1["default"];
